from __future__ import annotations

from abc import ABC
from typing import Any

from loguru import logger
from stable_baselines3.common.callbacks import BaseCallback

from src.utils import config


class TradingCallback(BaseCallback, ABC):
    """
    Base class for WARLOCK callbacks.

    Provides common helper methods for accessing environment information
    without duplicating logic across callbacks.
    """

    def __init__(self, verbose: int = 0) -> None:
        super().__init__(verbose)

    @property
    def callback_config(self) -> dict[str, Any]:
        """
        Returns the callback configuration section from config.yaml.
        """
        return config.get("callbacks", {})

    def latest_info(self) -> dict[str, Any]:
        """
        Returns the latest info dictionary produced by the environment.

        Stable-Baselines3 stores infos inside self.locals["infos"].
        This helper safely extracts the most recent entry.
        """
        infos = self.locals.get("infos")

        if not infos:
            return {}

        if isinstance(infos, list):
            return infos[-1] if infos else {}

        return {}

    def reward_components(self) -> dict[str, float]:
        """
        Returns the reward decomposition generated by the environment.
        """
        info = self.latest_info()

        reward = info.get("reward_components")

        if isinstance(reward, dict):
            return reward

        return {}

    def _on_training_start(self) -> None:
        logger.info("Training started.")

    def _on_training_end(self) -> None:
        logger.info("Training completed successfully.")
        
        
class PortfolioLoggingCallback(TradingCallback):
    """
    Logs custom portfolio and reward metrics to Stable-Baselines3's logger.

    SB3 automatically forwards these metrics to TensorBoard when a
    TensorBoard log directory is configured in the PPO model.
    """

    def __init__(
        self,
        log_frequency: int | None = None,
        verbose: int = 0,
    ) -> None:
        super().__init__(verbose)

        callback_cfg = self.callback_config

        self._log_frequency = (
            int(
                callback_cfg.get(
                    "portfolio_log_frequency",
                    callback_cfg.get("log_frequency", 1_000),
                )
            )
            if log_frequency is None
            else max(1, log_frequency)
        )

        self._last_log_step = 0

    def _should_log(self) -> bool:
        """
        Returns whether metrics should be recorded during this step.
        """
        return (
            self.num_timesteps - self._last_log_step
        ) >= self._log_frequency

    def _record_portfolio_metrics(
        self,
        info: dict[str, Any],
    ) -> None:
        """
        Records portfolio metrics.
        """

        self.logger.record(
            "portfolio/capital",
            float(info.get("capital", 0.0)),
        )

        self.logger.record(
            "portfolio/cash",
            float(info.get("cash", 0.0)),
        )

        self.logger.record(
            "portfolio/drawdown",
            float(info.get("drawdown", 0.0)),
        )

        self.logger.record(
            "portfolio/realized_pnl",
            float(info.get("realized_pnl", 0.0)),
        )

        self.logger.record(
            "portfolio/unrealized_pnl",
            float(info.get("unrealized_pnl", 0.0)),
        )

        self.logger.record(
            "portfolio/trades",
            int(info.get("n_trades_this_step", 0)),
        )

        self.logger.record(
            "portfolio/position_open",
            int(bool(info.get("weights"))),
        )

    def _record_reward_metrics(
        self,
        reward: dict[str, float],
    ) -> None:
        """
        Records reward decomposition.
        """

        self.logger.record(
            "reward/total",
            float(reward.get("total_reward", 0.0)),
        )

        self.logger.record(
            "reward/sharpe",
            float(reward.get("sharpe_reward", 0.0)),
        )

        self.logger.record(
            "reward/drawdown_penalty",
            float(reward.get("drawdown_penalty", 0.0)),
        )

        self.logger.record(
            "reward/overtrade_penalty",
            float(reward.get("overtrade_penalty", 0.0)),
        )
    
    def _log_console(
        self,
        info: dict[str, Any],
        reward: dict[str, float],
    ) -> None:
        """
        Writes a concise training summary to the console.
        """

        logger.info(
            (
                "[{:>10,d}] "
                "Capital={:>11.2f} | "
                "Cash={:>10.2f} | "
                "Reward={:>9.6f} | "
                "Drawdown={:>7.2%} | "
                "Trades={} | "
                "RealizedPnL={:>10.2f} | "
                "UnrealizedPnL={:>10.2f}"
            ).format(
                self.num_timesteps,
                float(info.get("capital", 0.0)),
                float(info.get("cash", 0.0)),
                float(reward.get("total_reward", 0.0)),
                float(info.get("drawdown", 0.0)),
                int(info.get("n_trades_this_step", 0)),
                float(info.get("realized_pnl", 0.0)),
                float(info.get("unrealized_pnl", 0.0)),
            )
        )

    def _on_step(self) -> bool:
        """
        Called after every environment step.

        Records portfolio statistics to Stable-Baselines3's logger and
        periodically prints a concise progress summary.
        """

        if not self._should_log():
            return True

        self._last_log_step = self.num_timesteps

        info = self.latest_info()

        if not info:
            return True

        reward = self.reward_components()

        self._record_portfolio_metrics(info)
        self._record_reward_metrics(reward)
        self._log_console(info, reward)

        self.logger.dump(self.num_timesteps)

        return True
    
from stable_baselines3.common.callbacks import (
    CallbackList,
    CheckpointCallback,
    EvalCallback,
)


class CallbackFactory:
    """
    Factory responsible for creating the callback pipeline used during
    training.
    """

    def __init__(
        self,
        experiment,
        eval_env,
    ) -> None:
        self._experiment = experiment
        self._eval_env = eval_env

        training_cfg = config["training"]

        self._checkpoint_frequency = int(
            training_cfg["checkpoint_frequency"]
        )

        self._evaluation_frequency = int(
            training_cfg["evaluation_frequency"]
        )

    def build(self) -> CallbackList:
        """
        Returns the callback list used by PPO.
        """

        checkpoint_callback = CheckpointCallback(
            save_freq=self._checkpoint_frequency,
            save_path=str(self._experiment.checkpoints_directory),
            name_prefix="checkpoint",
            save_replay_buffer=False,
            save_vecnormalize=False,
        )

        evaluation_callback = EvalCallback(
            eval_env=self._eval_env,
            best_model_save_path=str(self._experiment.run_directory),
            log_path=str(self._experiment.logs_directory),
            eval_freq=self._evaluation_frequency,
            deterministic=True,
            render=False,
        )

        portfolio_callback = PortfolioLoggingCallback()

        return CallbackList(
            [
                checkpoint_callback,
                evaluation_callback,
                portfolio_callback,
            ]
        )